# MIS: Clase Complementaria 3 

In [2]:
import numpy as np
import pandas as pd
import networkx as nx
import itertools as it
import time
import matplotlib.pyplot as plt
import graph_tools
import random
#import scipy.linalg as linalg 
#py -m pip install scipy==1.8.1


#### Katz

In [3]:
# Ejemplos
M = [[0.5,0.5],[0.1,0.9]]
N = [[0.9,0.09],[0.4,0.6]] 
U = [[0.4,0.6],[0.9,0]]

n = 10
Matriz0 = np.array([[random.randint(0,1) for i in range(n)] for j in range(n)])
Matriz0 = Matriz0 - np.diag(Matriz0.diagonal())
Triang = np.triu(Matriz0)
Matriz1 = Triang+Triang.T
Norm = Matriz1.sum(axis = 0)
Matriz = np.array([Matriz1[i]/Norm[i] for i in range(n)])



In [4]:
# Calculo de autovalores y autovectores
Katz = np.linalg.eig(M)
print(Katz)

(array([0.4, 1. ]), array([[-0.98058068, -0.70710678],
       [ 0.19611614, -0.70710678]]))


In [5]:
# Es buena aproximación?
index = [i for i in range(2) if Katz[0][i] == 1][0]
v = Katz[1][index]
derecha = M@v
Medida = v-derecha
print("Medida de error {}".format(np.abs(Medida).sum()))
print(np.abs(Medida))
print(v)
print(derecha)


Medida de error 0.5419337497948389
[0.45161146 0.09032229]
[ 0.19611614 -0.70710678]
[-0.25549532 -0.61678449]


In [6]:
# Será que calculamos Katz en esta?
Katz = np.linalg.eig(Matriz)
print(Katz)

(array([ 1.00000000e+00,  3.22392426e-01, -4.83255883e-01, -3.34910861e-01,
       -4.19355968e-01, -1.56671918e-01, -9.52297277e-02,  1.06831186e-01,
        6.02007447e-02, -1.99481025e-17]), array([[ 3.16227766e-01,  2.73035147e-01, -1.11543243e-01,
        -5.91233917e-01,  1.13939202e-02, -3.19773239e-01,
        -3.03582483e-01, -6.88475436e-02,  3.29559911e-01,
        -3.50829320e-17],
       [ 3.16227766e-01,  2.43640571e-01, -3.16314422e-01,
         1.53796310e-01, -4.12376469e-01, -1.51471940e-01,
         3.17690036e-01, -5.31041974e-01, -2.66718580e-01,
         2.64150623e-16],
       [ 3.16227766e-01, -2.86381547e-01,  4.58438927e-03,
         4.49710658e-01,  3.97658512e-01, -2.00857423e-01,
        -3.70322716e-01, -4.81068069e-01,  1.11440555e-01,
         3.72315130e-17],
       [ 3.16227766e-01,  7.87228116e-03, -1.93520027e-01,
        -1.02111735e-01,  9.44286845e-02,  7.84865668e-01,
        -1.25258269e-01,  3.38478955e-02, -1.00263095e-01,
        -1.96196433e

In [7]:
# Es buena aproximación?
v = Katz[1][0]
derecha = Matriz@v
Medida = v-derecha
print("Medida de error {}".format(np.abs(Medida).sum()))
print(np.abs(Medida))
print(v)
print(derecha)

Medida de error 2.819881885748976
[0.38442905 0.34460507 0.06251665 0.60528617 0.21337494 0.27599005
 0.18056226 0.01158852 0.40999597 0.33153322]
[ 3.16227766e-01  2.73035147e-01 -1.11543243e-01 -5.91233917e-01
  1.13939202e-02 -3.19773239e-01 -3.03582483e-01 -6.88475436e-02
  3.29559911e-01 -3.50829320e-17]
[-0.06820128 -0.07156992 -0.04902659  0.01405225 -0.20198102 -0.04378319
 -0.12302022 -0.08043606 -0.08043606 -0.33153322]


#### Bonanich

In [8]:
# Calculo de autovalores y autovectores
Bonanich = np.linalg.eig(Matriz1)
print(Bonanich)

(array([ 6.09730961e+00,  1.59531772e+00, -2.56253810e+00, -2.23098802e+00,
       -2.07914581e+00, -1.25859599e+00, -5.35999471e-01,  6.67180519e-01,
        3.07459537e-01, -1.42257284e-17]), array([[-3.59438013e-01,  3.39126087e-01, -7.79502846e-02,
         1.90028159e-01,  5.76082412e-01,  3.55891988e-01,
         3.53216579e-01,  5.63059410e-02,  3.56578882e-01,
        -3.40240852e-17],
       [-3.14164182e-01,  2.50137260e-01,  3.48495410e-01,
        -4.81262697e-01,  6.25432104e-02,  1.59980559e-01,
        -3.05569999e-01,  5.40731029e-01, -2.65331643e-01,
         1.36088054e-16],
       [-3.20927717e-01, -3.05841364e-01,  6.96212500e-02,
         2.80781173e-01, -5.56062248e-01,  1.32092980e-01,
         3.85743444e-01,  4.73267482e-01,  1.42644252e-01,
         1.14723448e-16],
       [-4.37367240e-01,  7.28412443e-03,  2.60784398e-01,
         2.31518707e-01,  2.03838836e-01, -7.91462337e-01,
         6.83069794e-02, -2.76477513e-02, -1.16851542e-01,
         1.31131793e

In [9]:
# Identificación del radio espectral
Lambda_Abs = np.abs(Bonanich[0])
indice = 0
for i in range(len(Lambda_Abs)):
    if Lambda_Abs[i] == Lambda_Abs.max():
        indice = i
        break
print(indice)

0


In [10]:
# Identificación de Bonanich
Bonanich[1][indice]

array([-3.59438013e-01,  3.39126087e-01, -7.79502846e-02,  1.90028159e-01,
        5.76082412e-01,  3.55891988e-01,  3.53216579e-01,  5.63059410e-02,
        3.56578882e-01, -3.40240852e-17])

#### PageRank

In [11]:
# Implementación del Page Rank
def pagerank(matriz,d=0.85,epsilon=0.00001):
    n,m=matriz.shape
    if n==m:
        I = np.identity(n)
        v_i = (1/n)*(np.ones(n).T)
        error = 1
        contador = 0
        while error>epsilon:
            v_f = (1-d)*I+d*(matriz@v_i)
            error=np.linalg.norm(v_f-v_i)
            contador += 1
            v_i = v_f
            print(error)
            if contador>200:
                error=0
        return v_f
    else:
        print("Error")
        return None 
# matriz =Matriz.T



In [12]:
PR = pagerank(Matriz.T,d=0.8)

0.6703219519562046
0.3267320836554735
0.12351846310950426
0.056599512106354874
0.03560954688249041
0.025901212807142332
0.020437105822172678
0.016216756369434825
0.012979387398613472
0.010372987079828524
0.008300876358133478
0.00663946578683982
0.0053119930002160885
0.004249423261383822
0.003399602507506301
0.0027196570953154724
0.0021757351975572954
0.0017405844799339557
0.001392468998759958
0.001113974653249057
0.0008911799329705655
0.0007129438652122607
0.0005703551234851324
0.00045628408670108
0.00036502727402689316
0.00029202181741982806
0.00023361745463169257
0.00018689396343660379
0.00014951517085307482
0.00011961213664236572
9.568970932939486e-05
7.655176745751531e-05
6.12414139683182e-05
4.89931311737826e-05
3.919450493936944e-05
3.135560395135795e-05
2.5084483161155544e-05
2.006758652887183e-05
1.6054069223100683e-05
1.2843255378489915e-05
1.0274604302813717e-05
8.219683442224288e-06


In [17]:
# Calculemos un pagerank de verdad

# Qué se está haciendo acá?
A = pd.read_csv(r"C:\Users\mateo\OneDrive\Desktop\MATEO\TRANSITORIO\Personal\2022_2\Complementarias\MIS\2022_20_MIS_C03_Twitter_Dataset\data\edges.csv")
A.columns = ["From","To"]
A = A.iloc[0:300,:]

In [18]:
# Qué se está haciendo acá?
AA = nx.from_pandas_edgelist(A,source="From",target="To",create_using=nx.DiGraph)
print("La red es dirigida: {}".format(nx.is_directed(AA)))
Matriz_A = nx.to_numpy_array(AA)

La red es dirigida: True


In [19]:
# Normalización
n = Matriz_A.shape[0]
Norm_A = Matriz_A.sum(axis = 1)
Quitar = [True if i>0 else False for i in Norm_A]
Reemplazo = [0 for i in range(n)]
Matriz = np.array([Matriz_A[i]/Norm_A[i] if Quitar[i] else Reemplazo for i in range(n)])




In [21]:
PR = pagerank(Matriz)

2.715284397677231
0.11970449433735951
0.009730639730639723
0.0


In [30]:
A.to_csv(r"C:\Users\mateo\OneDrive\Desktop\MATEO\TRANSITORIO\Personal\2022_2\Complementarias\MIS\2020_20_MIS_T1_Twitter.csv")

False

In [181]:
Matriz.sum(axis=1)

array([1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [141]:
Matriz = np.array([(Matriz_A[i][Quitar])/Norm_A[i] for i in range(n) if Quitar[i]])

In [153]:
Matriz_A==0

array([[ True, False, False, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [143]:
[(Matriz_A[i][Quitar])/Norm_A[i] for i in range(n) if Quitar[i]]

[array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [127]:
(Matriz==0).all()

True

In [118]:
A = np.array([[1,1],[0,2]])
A

array([[1, 1],
       [0, 2]])

In [122]:
A.sum(axis=0)

array([1, 3])

In [108]:
Matriz.sum(axis=0)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Actividad en clase

Realice los siguientes requerimientos:

1) Construya una función que le diga si puede calcular el índice de Katz para una matriz dada.

2) Cree el índice de Hubs.

3) Cree el índice de Authorities.