# MIS: Clase Complementaria 4 (2023-20)

In [ ]:
import numpy as np
import pandas as pd
import networkx as nx
import itertools as it
import time
import matplotlib.pyplot as plt
import graph_tools
import random
#import scipy.linalg as linalg 
#py -m pip install scipy==1.8.1


#### Katz

In [1]:
# Ejemplos
M = [[0.5,0.5],[0.1,0.9]]
N = [[0.9,0.09],[0.4,0.6]] 
U = [[0.4,0.6],[0.9,0]]

n = 10
Matriz0 = np.array([[random.randint(0,1) for i in range(n)] for j in range(n)])
Matriz0 = Matriz0 - np.diag(Matriz0.diagonal())
Triang = np.triu(Matriz0)
Matriz1 = Triang+Triang.T
Norm = Matriz1.sum(axis = 0)
Matriz = np.array([Matriz1[i]/Norm[i] for i in range(n)])



NameError: name 'np' is not defined

In [ ]:
# Calculo de autovalores y autovectores
Katz = np.linalg.eig(M)
print(Katz)

(array([0.4, 1. ]), array([[-0.98058068, -0.70710678],
       [ 0.19611614, -0.70710678]]))


In [ ]:
# Es buena aproximación?
index = [i for i in range(2) if Katz[0][i] == 1][0]
v = Katz[1][index]
derecha = M@v
Medida = v-derecha
print("Medida de error {}".format(np.abs(Medida).sum()))
print(np.abs(Medida))
print(v)
print(derecha)


Medida de error 0.5419337497948389
[0.45161146 0.09032229]
[ 0.19611614 -0.70710678]
[-0.25549532 -0.61678449]


In [ ]:
# Será que calculamos Katz en esta?
Katz = np.linalg.eig(Matriz)
print(Katz)

(array([ 1.        , -0.75212641,  0.49735439, -0.55166506, -0.34754616,
       -0.18694394, -0.11831094,  0.25993562,  0.13981832,  0.05948419]), array([[ 0.31622777,  0.24825917,  0.46380152,  0.10183659,  0.677572  ,
        -0.08474547, -0.31557297, -0.07586642, -0.47205042,  0.06751781],
       [ 0.31622777,  0.25619475, -0.04467775, -0.47276658,  0.10064225,
         0.28781081, -0.18500395, -0.45853315,  0.48439046,  0.1539348 ],
       [ 0.31622777, -0.29150743,  0.0449159 , -0.14268058, -0.10379756,
        -0.38100324,  0.28745294, -0.1774223 , -0.12170343,  0.45166548],
       [ 0.31622777, -0.18049486,  0.34210371, -0.39484112, -0.37888786,
        -0.11765844, -0.48269909,  0.28077119, -0.02765123, -0.34660674],
       [ 0.31622777,  0.29910279, -0.04767404, -0.10932246,  0.09333573,
        -0.21493788,  0.5140659 ,  0.21983992,  0.10300435, -0.35417448],
       [ 0.31622777,  0.08382239, -0.04054193,  0.50978344, -0.02040643,
        -0.15852416, -0.27731196,  0.31046628

In [ ]:
# Es buena aproximación?
v = Katz[1][0]
derecha = Matriz@v
Medida = v-derecha
print("Medida de error {}".format(np.abs(Medida).sum()))
print(np.abs(Medida))
print(v)
print(derecha)

Medida de error 3.9100469549476013
[0.28503187 0.350401   0.33833805 0.00741438 0.74133819 0.36786604
 0.64668929 0.2959812  0.83358983 0.0433971 ]
[ 0.31622777  0.24825917  0.46380152  0.10183659  0.677572   -0.08474547
 -0.31557297 -0.07586642 -0.47205042  0.06751781]
[ 0.0311959  -0.10214183  0.12546348  0.10925097 -0.06376619  0.28312057
  0.33111633  0.22011478  0.36153941  0.02412071]


#### Bonanich

In [ ]:
# Calculo de autovalores y autovectores
Bonanich = np.linalg.eig(Matriz1)
print(Bonanich)

(array([ 4.51786111,  1.68144093, -3.00665864, -2.451769  ,  1.02714927,
        0.5105661 ,  0.25785709, -1.1566633 , -0.55106638, -0.82871718]), array([[-0.24527553, -0.43900981,  0.26171256,  0.05052411, -0.09662482,
        -0.43105842,  0.08066243, -0.61355749,  0.31073031, -0.03746857],
       [-0.30239541,  0.06395968,  0.28116295, -0.41063907, -0.4573242 ,
         0.52371505,  0.10637708, -0.01405883,  0.16639581, -0.36628532],
       [-0.41998789, -0.0285357 , -0.44872711, -0.22635586, -0.28403122,
        -0.11651081,  0.4538666 ,  0.02321847, -0.22246391,  0.46896718],
       [-0.31208656, -0.33617276, -0.23099427, -0.36063966,  0.35752835,
        -0.0501578 , -0.31321269,  0.40725116,  0.46018098,  0.01029536],
       [-0.41917976,  0.11180664,  0.45903621, -0.18835788,  0.30301674,
         0.04673999, -0.35859877, -0.12580504, -0.48948454,  0.29593208],
       [-0.36946211,  0.13540913,  0.08093107,  0.55891682,  0.33358829,
         0.41212476,  0.31702676, -0.01089974

In [ ]:
# Identificación del radio espectral
Lambda_Abs = np.abs(Bonanich[0])
indice = 0
for i in range(len(Lambda_Abs)):
    if Lambda_Abs[i] == Lambda_Abs.max():
        indice = i
        break
print(indice)

0


In [ ]:
# Identificación de Bonanich
Bonanich[1][indice]

array([-0.24527553, -0.43900981,  0.26171256,  0.05052411, -0.09662482,
       -0.43105842,  0.08066243, -0.61355749,  0.31073031, -0.03746857])

#### PageRank

In [20]:
# Implementación del Page Rank
def pagerank(matriz,d=0.85,epsilon=0.00001):
    n,m=matriz.shape
    if n==m:
        I = np.identity(n)
        v_i = (1/n)*(np.ones(n).T)
        error = 1
        contador = 0
        while error>epsilon:
            v_f = (1-d)*I+d*(matriz@v_i)
            error=np.linalg.norm(v_f-v_i)
            contador += 1
            v_i = v_f
            print(error)
            if contador>200:
                error=0
        return v_f
    else:
        print("Error")
        return None 
# matriz =Matriz.T



In [24]:
PR = pagerank(Matriz.T,d=0.8)


0.6447325026706812
0.31109811985574226
0.1074872861069333
0.06052243082063405
0.038464064679764036
0.02634127511515311
0.01896833317377166
0.01419209751569212
0.010891168831362921
0.008501117160915058
0.0067025307804104775
0.005317797741124465
0.0042337147937545954
0.0033778909309268856
0.00269805260905366
0.0021565965066199302
0.0017243903736273254
0.0013791412319150986
0.001103126668260242
0.0008824279909823287
0.0007059025808263454
0.0005647080184080207
0.00045175766717764175
0.0003614036116390453
0.0002891208833457545
0.00023129631876069856
0.0001850365666265543
0.0001480292204553339
0.00011842324827653034
9.473860877115942e-05
7.579085062513209e-05
6.063268868989482e-05
4.8506139821033576e-05
3.88049157467566e-05
3.104392898628413e-05
2.483514478681068e-05
1.986811460785756e-05
1.5894492303523865e-05
1.271559341814892e-05
1.017247496594179e-05
8.137979822575296e-06


In [26]:
PR

array([[0.26413779, 0.04669436, 0.06989134, 0.08803514, 0.04751961,
        0.04592009, 0.03506315, 0.03485576, 0.08260532, 0.0372816 ],
       [0.06225627, 0.27365425, 0.08567327, 0.06031286, 0.06494062,
        0.08688184, 0.1082319 , 0.0584247 , 0.08749503, 0.06728646],
       [0.13976951, 0.12850104, 0.30065923, 0.09879454, 0.11171614,
        0.11778916, 0.09936092, 0.09650258, 0.12471207, 0.1324038 ],
       [0.11737732, 0.06031286, 0.06586894, 0.27736756, 0.08499532,
        0.08752603, 0.05123156, 0.05848718, 0.09694859, 0.04682187],
       [0.09502605, 0.09740206, 0.11171614, 0.12748411, 0.30072179,
        0.12450929, 0.13362347, 0.14085022, 0.11717762, 0.10298169],
       [0.07652652, 0.10859893, 0.09816164, 0.10940416, 0.10376175,
        0.28731053, 0.07810215, 0.12575705, 0.07943381, 0.08053701],
       [0.03506213, 0.08117507, 0.04968603, 0.03842481, 0.0668173 ,
        0.04686446, 0.26594569, 0.05679527, 0.04338726, 0.09931273],
       [0.03485512, 0.04382004, 0.0482572

### Actividad en clase

Realice los siguientes requerimientos:

1) Construya una función que le diga si puede calcular el índice de Katz para una matriz dada.

2) Cree el índice de Hubs.

3) Cree el índice de Authorities.